name: Rerun workflow

on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true

jobs:
  rerun:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node18.12.0-chrome107
      options: "-u root:root"
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Execucao Suite TAT
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:execute

      - name: rerun ${{ inputs.run_id }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.PAT_WORKFLOW_DISPATCH }}
          GH_DEBUG: api
        run: |
          gh run watch ${{ inputs.run_id }} > /dev/null 2>&1
          gh run rerun ${{ inputs.run_id }} --failed